### ISSUE TITLE
[ROADMAP] Develop new content and guidance for ROR websites

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-roadmap#133]
New content and guidance is needed to drive adoption and support adopters. Potential content to be developed includes:

General ROR website:
- "Case Studies" blog series
- Comparison chart of the features and services of ROR vs other identifiers
- Events calendar listing upcoming and previous events
- Links to ROR presentations, including recordings and slide decks
- Adoption statistics including the number of DOIs with ROR IDs in Crossref and DataCite
- Updated and comprehensive integrations list with more screenshots and informational links for each
- Bibliography of ROR research

Video shorts and tutorials:
- Following an affiliation through the publication process
- Introduction to ROR (updated as needed)
- Introduction to the ROR API: query, query.advanced, affiliation

Technical documentation:
- Typeahead guidelines
- Documentation for specific use cases (e.g., integrate ROR API, match text strings to ROR IDs)
- Best practices for ROR in repositories
- Code samples

**Comment by amandafrench** [comment]
General ROR website:  

- [x]  "Case Studies" blog series
- [ ]     Comparison chart of the features and services of ROR vs other identifiers
- [x]     Events calendar listing upcoming and previous events
- [x]     Links to ROR presentations, including recordings and slide decks
- [x]     Adoption statistics including the number of DOIs with ROR IDs in Crossref and DataCite
- [ ]     Updated and comprehensive integrations list with more screenshots and informational links for each
- [x]     Bibliography of ROR research

Video shorts and tutorials:

- [ ]     Following an affiliation through the publication process
- [ ]     Introduction to ROR (updated as needed)
- [x]    Introduction to the ROR API ?query
- [ ]     Introduction to the ROR API ?query.advanced
- [ ]     Introduction to the ROR API ?affiliation

Technical documentation:

- [x]     Typeahead guidelines
- [x]     Documentation for specific use cases (e.g., integrate ROR API, match text strings to ROR IDs)
- [ ]     Best practices for ROR in institutional repositories
- [ ]     Code samples

**Comment by amandafrench** [comment]
Closing this as it will be replaced by new ror-adoption repository
