### ISSUE TITLE
[ROADMAP] Publish annual report and financial overview

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-roadmap#18]
**Description:**
In 2021, ROR published a report to document and communicate its progress and activities from the prior year. We plan to produce this report on a regular basis going forward. As ROR becomes more established and as we continue to build a foundation for long-term sustainability, we also plan to make ROR's financial activities more transparent by publishing resourcing information on the ROR website. 

**Work related to this roadmap item:**

- [ ] Produce annual report for 2022/2023 
- [ ] Publish 2022 financial overview on ROR website
- [ ] Establish regular schedule/process for publishing these items going forward

**Comment by mariagould** [comment]
Closing as we are rescoping this project to be focused on product development work. Operational and strategic activities will be tracked separately.
